// Package api Code generated by swaggo/swag. DO NOT EDIT
package api

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Check the health and connectivity of the service and Solana RPC",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Health check endpoint",
                "responses": {
                    "200": {
                        "description": "Service is healthy",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "503": {
                        "description": "Service is unhealthy - Solana RPC issues",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/wallet/{address}/balances": {
            "get": {
                "description": "Fetch balances for hyUSD, sHYUSD, and xSOL tokens for a specific wallet address",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wallet"
                ],
                "summary": "Get wallet token balances",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Wallet address (base58 encoded)",
                        "name": "address",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Wallet token balances",
                        "schema": {
                            "$ref": "#/definitions/hylo-wallet-tracker-api_internal_tokens.WalletBalances"
                        }
                    },
                    "400": {
                        "description": "Invalid wallet address",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "Failed to fetch balances",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "hylo-wallet-tracker-api_internal_tokens.TokenBalance": {
            "type": "object",
            "properties": {
                "decimal_amount": {
                    "description": "DecimalAmount is the human-readable amount adjusted for token decimals",
                    "type": "string"
                },
                "raw_amount": {
                    "description": "RawAmount is the raw token amount as stored on-chain (without decimal adjustment)",
                    "type": "integer"
                },
                "token_info": {
                    "description": "TokenInfo contains the token metadata",
                    "allOf": [
                        {
                            "$ref": "#/definitions/hylo-wallet-tracker-api_internal_tokens.TokenInfo"
                        }
                    ]
                },
                "usd_value": {
                    "description": "USDValue is the USD value of this token balance (optional, for display)",
                    "type": "number"
                }
            }
        },
        "hylo-wallet-tracker-api_internal_tokens.TokenInfo": {
            "type": "object",
            "properties": {
                "decimals": {
                    "description": "Decimals is the number of decimal places for this token",
                    "type": "integer"
                },
                "mint": {
                    "description": "Mint is the Solana mint address for this token",
                    "type": "string"
                },
                "name": {
                    "description": "Name is the human-readable display name",
                    "type": "string"
                },
                "symbol": {
                    "description": "Symbol is the short identifier (e.g., \"hyUSD\", \"xSOL\")",
                    "type": "string"
                }
            }
        },
        "hylo-wallet-tracker-api_internal_tokens.WalletBalances": {
            "type": "object",
            "properties": {
                "balances": {
                    "description": "Balances is a map of token symbol to token balance",
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/hylo-wallet-tracker-api_internal_tokens.TokenBalance"
                    }
                },
                "slot": {
                    "description": "Slot is the Solana slot when these balances were fetched",
                    "type": "integer"
                },
                "total_usd_value": {
                    "description": "TotalUSDValue is the sum of all token balances in USD (optional)",
                    "type": "number"
                },
                "updated_at": {
                    "description": "UpdatedAt is the timestamp when these balances were last updated",
                    "type": "string"
                },
                "wallet": {
                    "description": "Wallet is the wallet address these balances belong to",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http", "https"},
	Title:            "Hylo Wallet Tracker API",
	Description:      "Read-only REST API for tracking Solana wallet activity and metrics for the Hylo protocol. Provides real-time wallet balances (hyUSD, sHYUSD, xSOL), price data (SOL/USD, xSOL pricing), and transaction history.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
