basePath: /
consumes:
- application/json
definitions:
  hylo-wallet-tracker-api_internal_hylo.XSOLTrade:
    properties:
      blockTime:
        description: Unix timestamp
        type: integer
      counterAmount:
        description: Formatted counter-asset amount
        type: string
      counterAsset:
        description: '"SOL", "hyUSD", "USDC", etc.'
        type: string
      explorerUrl:
        description: Solscan transaction URL
        type: string
      historical_price_usd:
        description: Historical pricing (new field)
        type: string
      side:
        description: Trade details
        type: string
      signature:
        description: Transaction identifiers
        type: string
      slot:
        description: Solana slot number
        type: integer
      timestamp:
        description: Display fields
        type: string
      xsolAmount:
        description: Formatted xSOL amount (e.g., "1.5")
        type: string
    type: object
  hylo-wallet-tracker-api_internal_price.CombinedPriceResponse:
    properties:
      sol_usd:
        description: SOLUSD is the current SOL price in USD
        type: number
      updated_at:
        description: UpdatedAt indicates the timestamp of the most recent price update
        type: string
      xsol_sol:
        description: XSOLInSOL is the current xSOL price in SOL terms
        type: number
      xsol_usd:
        description: XSOLInUSD is the current xSOL price in USD terms
        type: number
    type: object
  hylo-wallet-tracker-api_internal_tokens.TokenBalance:
    properties:
      decimals:
        description: Decimals is the number of decimal places for this token
        type: integer
      formatted_amount:
        description: FormattedAmount is the human-readable amount with proper decimal
          adjustment
        type: string
      raw_amount:
        description: RawAmount is the raw token amount as stored on-chain (without
          decimal adjustment)
        type: integer
      usd_value:
        description: USDValue is the USD value of this token balance (optional, for
          display)
        type: number
    type: object
  hylo-wallet-tracker-api_internal_tokens.WalletBalances:
    properties:
      balances:
        additionalProperties:
          $ref: '#/definitions/hylo-wallet-tracker-api_internal_tokens.TokenBalance'
        description: Balances is a map of token symbol to token balance
        type: object
      slot:
        description: Slot is the Solana slot when these balances were fetched
        type: integer
      total_usd_value:
        description: TotalUSDValue is the sum of all token balances in USD (optional)
        type: number
      updated_at:
        description: UpdatedAt is the timestamp when these balances were last updated
        type: string
      wallet:
        description: Wallet is the wallet address these balances belong to
        type: string
    type: object
  hylo-wallet-tracker-api_internal_trades.PaginationInfo:
    properties:
      count:
        description: Count is the number of items in the current response
        type: integer
      hasMore:
        description: HasMore indicates if there are more trades available
        type: boolean
      limit:
        description: Limit is the maximum number of items per page
        type: integer
      nextCursor:
        description: |-
          NextCursor is the signature cursor for the next page
          Only present when HasMore is true
        type: string
    type: object
  hylo-wallet-tracker-api_internal_trades.TradeResponse:
    properties:
      count:
        description: Number of trades returned
        type: integer
      pagination:
        allOf:
        - $ref: '#/definitions/hylo-wallet-tracker-api_internal_trades.PaginationInfo'
        description: Pagination metadata for frontend navigation
      requestedAt:
        type: string
      trades:
        description: Trades is the array of xSOL trades for this wallet
        items:
          $ref: '#/definitions/hylo-wallet-tracker-api_internal_hylo.XSOLTrade'
        type: array
      walletAddress:
        description: Request metadata
        type: string
    type: object
  internal_server.ErrorResponse:
    properties:
      code:
        description: For categorizing errors
        type: string
      details:
        type: string
      error:
        type: string
      request_id:
        type: string
      timestamp:
        type: string
    type: object
  internal_server.HealthResponse:
    properties:
      solana: {}
      status:
        type: string
      timestamp:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    name: API Support
  description: Read-only REST API for tracking Solana wallet activity and metrics
    for the Hylo protocol. Provides real-time wallet balances (hyUSD, sHYUSD, xSOL),
    price data (SOL/USD, xSOL pricing), and transaction history.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  termsOfService: http://swagger.io/terms/
  title: Hylo Wallet Tracker API
  version: "1.0"
paths:
  /health:
    get:
      description: Check the health and connectivity of the service and Solana RPC
      produces:
      - application/json
      responses:
        "200":
          description: Service is healthy
          schema:
            $ref: '#/definitions/internal_server.HealthResponse'
        "503":
          description: Service is unhealthy - Solana RPC issues
          schema:
            $ref: '#/definitions/internal_server.HealthResponse'
      summary: Health check endpoint
      tags:
      - health
  /price:
    get:
      description: Fetch current prices for SOL/USD, xSOL/SOL, and xSOL/USD with caching
      produces:
      - application/json
      responses:
        "200":
          description: Current asset prices
          schema:
            $ref: '#/definitions/hylo-wallet-tracker-api_internal_price.CombinedPriceResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "502":
          description: Network connectivity error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Get current asset prices
      tags:
      - price
  /wallet/{address}/balances:
    get:
      description: Fetch balances for hyUSD, sHYUSD, and xSOL tokens for a specific
        wallet address
      parameters:
      - description: Wallet address (base58 encoded)
        in: path
        name: address
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Wallet token balances
          schema:
            $ref: '#/definitions/hylo-wallet-tracker-api_internal_tokens.WalletBalances'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "502":
          description: Network connectivity error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Get wallet token balances
      tags:
      - wallet
  /wallet/{address}/trades:
    get:
      description: Fetch paginated xSOL trade history for a specific wallet address
        with real-time RPC data
      parameters:
      - description: Wallet address (base58 encoded)
        in: path
        name: address
        required: true
        type: string
      - description: Maximum number of trades to return (1-50, default 10)
        in: query
        name: limit
        type: integer
      - description: Cursor for pagination - signature to fetch trades before
        in: query
        name: before
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Wallet xSOL trade history
          schema:
            $ref: '#/definitions/hylo-wallet-tracker-api_internal_trades.TradeResponse'
        "400":
          description: Validation error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
        "502":
          description: Network connectivity error
          schema:
            $ref: '#/definitions/internal_server.ErrorResponse'
      summary: Get wallet xSOL trade history
      tags:
      - wallet
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
